spring:
  flyway:
    # ????????????????? flyway_schema_history ???????????
    # ????? false??????????????
    # ????? true???? history ????????????????????
    baseline-on-migrate: false
    baseline-description: << Flyway Baseline >>
    # ???? flyway
    enabled: true
    # ????????????????????????
    check-location: true
    # ????
    locations: classpath:db/migration
    # ?????????????? v1_??.sql ???????????????????????????????
    validate-on-migrate: true
    # ??????????????????????
    clean-on-validation-error: false
  application:
    name: Gradle-Demo
  datasource:
    url: jdbc:mysql://****/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: *
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    # Druid ? wall ?????????? SQL ?????????? Flyway ???
    druid:
      wall:
        config:
          variantCheck: false
          noneBaseStatementAllow: true
          commentAllow: true
          multiStatementAllow: true

#Mybatis??????????????????????????
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  config-location: classpath:mybatis.xml